version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
    ports:
      - 9090:9090
    networks:
      - "monitoring-network"
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8081:8081
    command:
    - '-port=8081'
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000  
    volumes:
      - grafanadata:/var/lib/grafana 
    networks:
      - "monitoring-network"
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    networks:
      - "monitoring-network"      
  jaeger:
    image: jaegertracing/all-in-one:1.19
    container_name: jaeger
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411    
    networks:
      - "monitoring-network"
networks:
  monitoring-network:
    driver: bridge
    
volumes:
  grafanadata:
