version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
    ports:
      - 9090:9090
    networks:
      - monitoring-network
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    command: ["-docker_only", "-v=4", "--url_base_prefix=/cadvisor"]
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080/cadvisor/healthz || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys/fs/cgroup:/cgroup:ro
    depends_on:
      - redis
    networks:
      - monitoring-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
    networks:
      - monitoring-network
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000  
    volumes:
      - grafanadata:/var/lib/grafana 
    networks:
      - monitoring-network
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    networks:
      - monitoring-network      
  jaeger:
    image: jaegertracing/all-in-one:1.19
    container_name: jaeger
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411    
    networks:
      - monitoring-network
networks:
  monitoring-network:
    driver: overlay
    
volumes:
  grafanadata:
